---
title: "Check if Bovy's Matrices Actually Do Only Span Same Space"
author: "David Gerard"
date: "March 21, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Abstract

I want to know if Bovy's EM algorithm will only create matrices that span the same space as the initial conditions.

# Analysis

First, I generate some fake data

```{r}
set.seed(25)
library(abind)
n <- 100
p <- 100
ydata <- matrix(rnorm(n * p), nrow = n)
ycovar <- array(NA, dim = c(n, p, p))
ycov_list <- lapply(rep(p, n), FUN = stats::rchisq, df = 1)
for (index in 1:n) {
  ycovar[index, , ] <- diag(ycov_list[[index]])
}


K <- 3 ## number of mixtures
xamp <- runif(K) ## initial mixture proportions
xamp <- xamp / sum(xamp)

## Here, I assume that observed and true data have same dimension
xmean <- matrix(0, nrow = K, ncol = p) ## initial mixture means

xcovar <- array(NA, dim = c(K, p, p)) ## initial covariance matrices

v1 <- matrix(rnorm(p), ncol = 1)
xcovar[1,,] <- tcrossprod(v1) ## the rank 1 psd matrix

xcovar[2,,] <- diag(p) ## full rank identity

V3 <- matrix(rnorm(p * p), nrow = p) ## full rank pd matrix
xcovar[3,,] <- tcrossprod(V3)
```

```{r, error=TRUE}
library(ExtremeDeconvolution)

eout <- extreme_deconvolution(ydata = ydata, ycovar = ycovar,
                              xamp = xamp, xmean = xmean, xcovar = xcovar,
                              fixmean = TRUE)

```


```{r}
sessionInfo()
```
