---
title: "Home"
output:
  html_document:
    toc: false
---

This project is about coming up with a better way to estimate low-rank matrices in the multivariate Gaussian deconvolution problem.

* [Bovy always returns rank-1 matrix in same span as initial conditions](check_bovy.html). That is, we just get a scaled estimate of the intial vector.
* [My UltimateDeconvolution does not result in estimates in the same span as the original](check__ultimate.html). I also show that the likelihood increases at every fixed-point iteration.
* [I need to work on my speed](profile_densities.html). Even the density calculation is super slow even though I have more information (low rank + diagonal)! I will probably write everything up in C.
* [Simple C++ density function is 20 times faster than mvtnorm function](profile_densities2.html).
* [Simple C++ likelihood calculation is 200 times faster in C++ than in R](profile_densities3.html).
* [C++ version of EM algorithm is 200 times faster than the R version](profile_em.html).
* [I increase the log-likelihood, Bovy decreases the log-likelihood](compare_bovy_ultimate.html). Do I have a bug somewhere in the Bovy implementation?
