---
title: "Profile New Densities"
author: "David Gerard"
date: "March 23, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

Here, I compare the speeds to my `dr1_norm` (R version) and `dnorm_rank1` (C++ version) from the [UltimateDeconvolution](https://github.com/dcgerard/UltimateDeconvolution) package and `dmvnorm` from the `mvtnorm` R package. Since I am using more information (rank 1 + diagonal), mine should be faster. My R version is about 2-3 times slower than `dmvnorm`, but my C++ version is about 10-20 times faster.


```{r}
library(microbenchmark)
library(UltimateDeconvolution)
set.seed(17)
R <- 11
x <- stats::rnorm(R)
s_diag <- stats::rchisq(R, df = 5)
v <- stats::rnorm(R)
mu <- rep(0, length(x))
log <- TRUE
true_cov <- tcrossprod(v) + diag(s_diag)

melist1 <- list(x = x, v = v, s_diag = s_diag,
                mu = mu, log = log)
melist2 <- list(x = x, v = v, s_diag = s_diag,
                mu = mu, return_log = log)

themlist <- list(x = x, mean = mu,
                 sigma = true_cov, log = log)

microbenchmark(
  do.call(dr1_norm, melist1),
  do.call(dnorm_rank1, melist2),
  do.call(mvtnorm::dmvnorm, themlist)
)
```

The log-likelihoods are also the same.

```{r}
medense1 <- dr1_norm(x = x, v = v, s_diag = s_diag,
                     mu = mu, log = log)
medense2 <- dnorm_rank1(x = x, v = v, s_diag = s_diag,
                        mu = mu, return_log = log)
themdense <- mvtnorm::dmvnorm(x = x, mean = mu,
                              sigma = true_cov, log = log)

medense1
medense2
themdense
```
